apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ldap-slave
  labels:
    app: ldap-slave
spec:
  selector:
    matchLabels:
      app: ldap-slave
  replicas: 1 
  template:
    metadata:
      labels:
        app: ldap-slave
    spec:
      containers:
      - name: slave
        image: 192.168.0.20:5000/ldap:slave
        ports:
        - containerPort: 389
        env:
          - name: IPMASTER
            value: "master-service"

