apiVersion: v1
kind: Service
metadata:
  name: slave-service
spec:
  type: NodePort
  selector:
    app: ldap-slave
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
      nodePort: 30008
