apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  type: NodePort
  selector:
    app: ldap-master
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
      nodePort: 30007
volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}